name: build & deploy java code
on:
  workflow_dispatch
jobs:
  docker_deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      -  name: code checkout
         uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .
          
      #- name: Login to Docker Hub
       # uses: docker/login-action@v3
        #with:
         # username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}
      #- name: Build and push
       # uses: docker/build-push-action@v5
        #with:
         # push: true
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/image_push_dochub:${{ github.sha }}
          #file: Dockerfile

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
            app-name: ${{secrets.WEB_APP_NAME}}
            #images: ${{ secrets.DOCKERHUB_USERNAME }}/image_push_dochub:${{ github.sha }}
            publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE}}
